import { Component, inject, signal, computed, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { AuthService } from '../login/auth.service';
import { MasterService } from '../../service/master.service';
import { toast } from 'ngx-sonner';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

@Component({
  selector: 'app-emi-calculator',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './emi-calculator.component.html',
  styleUrls: ['./emi-calculator.component.css']
})
export class EmiCalculatorComponent implements OnInit {
  private http = inject(HttpClient);
  private authService = inject(AuthService);
  private masterService = inject(MasterService);

  // Calculator inputs
  loanAmount = signal<number>(500000);
  interestRate = signal<number>(10.5);
  tenure = signal<number>(60); // months
  tenureType: 'months' | 'years' = 'months';

  // Results
  emi = signal<number>(0);
  totalInterest = signal<number>(0);
  totalPayment = signal<number>(0);

  // Eligibility inputs
  monthlyIncome = signal<number>(50000);
  existingEmi = signal<number>(0);
  creditScore = signal<number>(750);
  
  // Eligibility results
  eligibleAmount = signal<number>(0);
  maxEmi = signal<number>(0);
  isEligible = signal<boolean>(false);
  eligibilityMessage = signal<string>('');

  // For amortization table
  showAmortization = signal<boolean>(false);
  amortizationSchedule: any[] = [];

  // For saving calculations
  currentUser = this.authService.currentUserSignal;
  savedCalculations: any[] = [];

  ngOnInit() {
    this.calculateEMI();
    if (this.currentUser()) {
      this.loadUserSalary(); // Pre-fill salary from latest application
    }
  }

  calculateEMI() {
    const amount = this.loanAmount();
    const rate = this.interestRate();
    let tenure = this.tenure();
    if (this.tenureType === 'years') tenure *= 12;

    this.http.post<any>('http://localhost:3000/api/calculate-emi', {
      amount, rate, tenure, tenureType: 'months'
    }).subscribe({
      next: (res) => {
        this.emi.set(res.emi);
        this.totalInterest.set(res.totalInterest);
        this.totalPayment.set(res.totalPayment);
      },
      error: () => toast.error('Failed to calculate EMI')
    });
  }

  checkEligibility() {
    this.http.post<any>('http://localhost:3000/api/check-eligibility', {
      monthlyIncome: this.monthlyIncome(),
      existingEmi: this.existingEmi(),
      creditScore: this.creditScore(),
      requestedAmount: this.loanAmount(),
      tenureMonths: this.tenureType === 'months' ? this.tenure() : this.tenure() * 12
    }).subscribe({
      next: (res) => {
        this.eligibleAmount.set(res.eligibleAmount);
        this.maxEmi.set(res.maxEmi);
        this.isEligible.set(res.isEligible);
        this.eligibilityMessage.set(res.message);
      },
      error: () => toast.error('Eligibility check failed')
    });
  }

  generateAmortization() {
    const principal = this.loanAmount();
    const monthlyRate = this.interestRate() / (12 * 100);
    const monthlyEMI = this.emi();
    let balance = principal;
    const schedule = [];

    for (let i = 1; i <= (this.tenureType === 'months' ? this.tenure() : this.tenure() * 12); i++) {
      const interest = balance * monthlyRate;
      const principalPaid = monthlyEMI - interest;
      balance -= principalPaid;
      schedule.push({
        month: i,
        openingBalance: Math.round(balance + principalPaid),
        emi: Math.round(monthlyEMI),
        interest: Math.round(interest),
        principal: Math.round(principalPaid),
        closingBalance: Math.round(Math.max(balance, 0))
      });
      if (balance <= 0) break;
    }
    this.amortizationSchedule = schedule;
    this.showAmortization.set(true);
  }

exportToPDF() {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // 1. HEADER (Green Bar)
    doc.setFillColor(25, 135, 84); // Green color
    doc.rect(0, 0, pageWidth, 20, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('EMI Calculation Report', 14, 13);

    doc.setFontSize(10);
    doc.text('Generated by Finance App', pageWidth - 50, 13);

    // 2. LOAN SUMMARY SECTION
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text('Loan Details', 14, 35);
    doc.setDrawColor(200, 200, 200);
    doc.line(14, 38, 50, 38); // Underline

    // Helper to format currency for PDF (Using Rs. instead of ₹ to avoid bugs)
    const fmt = (num: number) => `Rs. ${num.toLocaleString('en-IN')}`;

    // Left Column (Inputs)
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Loan Amount:`, 14, 50);
    doc.text(`Interest Rate:`, 14, 60);
    doc.text(`Tenure:`, 14, 70);

    doc.setFont('helvetica', 'bold');
    doc.text(`${fmt(this.loanAmount())}`, 50, 50);
    doc.text(`${this.interestRate()}%`, 50, 60);
    doc.text(`${this.tenure()} ${this.tenureType}`, 50, 70);

    // Right Column (Results)
    doc.setFont('helvetica', 'normal');
    doc.text(`Monthly EMI:`, 110, 50);
    doc.text(`Total Interest:`, 110, 60);
    doc.text(`Total Payment:`, 110, 70);

    doc.setFont('helvetica', 'bold');
    doc.setTextColor(25, 135, 84); // Green for EMI
    doc.text(`${fmt(this.emi())}`, 150, 50);
    
    doc.setTextColor(0, 0, 0); // Reset black
    doc.text(`${fmt(this.totalInterest())}`, 150, 60);
    doc.text(`${fmt(this.totalPayment())}`, 150, 70);

    // 3. AMORTIZATION TABLE
    if (this.showAmortization()) {
      doc.setFontSize(14);
      doc.text('Amortization Schedule', 14, 90);
      doc.line(14, 93, 70, 93);

      const tableData = this.amortizationSchedule.map(row => [
        row.month,
        fmt(row.openingBalance),
        fmt(row.emi),
        fmt(row.interest),
        fmt(row.principal),
        fmt(row.closingBalance)
      ]);

      autoTable(doc, {
        startY: 100,
        head: [['Month', 'Opening', 'EMI', 'Interest', 'Principal', 'Closing']],
        body: tableData,
        theme: 'grid',
        headStyles: { 
          fillColor: [41, 58, 82], // Dark Blue header
          textColor: 255, 
          fontStyle: 'bold' 
        },
        styles: { 
          fontSize: 9, 
          cellPadding: 3 
        },
        alternateRowStyles: { 
          fillColor: [245, 245, 245] 
        },
        columnStyles: {
          0: { cellWidth: 20, halign: 'center' }, // Month column
          1: { halign: 'right' },
          2: { halign: 'right' },
          3: { halign: 'right' },
          4: { halign: 'right' },
          5: { halign: 'right' }
        }
      });
    }

    // 4. FOOTER
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });
    }

    doc.save(`EMI_Report_${new Date().getTime()}.pdf`);
  }


  loadUserSalary() {
    // For simplicity, we fetch the user's latest application to get salary
    this.masterService.getAllApplications(1, 1, '', '').subscribe({
      next: (res: any) => {
        const latest = res.loans[0];
        if (latest && latest.salary) {
          this.monthlyIncome.set(latest.salary / 12); // Assuming salary is annual
        }
      }
    });
  }

  // Slider formatters
  formatLabel(value: number): string {
    if (value >= 100000) return '₹' + (value / 100000).toFixed(1) + 'L';
    if (value >= 1000) return '₹' + (value / 1000).toFixed(0) + 'k';
    return '₹' + value;
  }
}